create table author (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table book (
    id bigint generated by default as identity,
    title varchar(255),
    primary key (id)
);

create table book_author (
    book_id bigint not null,
    author_id bigint not null
);

alter table book_author add constraint fk_author_id foreign key (author_id) references author;
alter table book_author add constraint fk_book_id foreign key (book_id) references book;