create table author (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table book (
    id bigint generated by default as identity,
    title varchar(255),
    author_id bigint,
    primary key (id)
);

alter table book add constraint fk_author_id foreign key (author_id) references author